/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class NDrugDetails extends javax.swing.JFrame {

    /**
     * Creates new form NDrugDetails
     */
    Boolean result;
    Connection con1;
    PreparedStatement insert;
    PreparedStatement insert2;
    public NDrugDetails() {
        initComponents();
        setimg();
        updateCombo();
    }
    
    public void setimg()
    {
        ImageIcon imageicon = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\icon.png");
        Image img = imageicon.getImage();
        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
        
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        backg.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){

                ImageIcon im = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\backg1.jpg");
                Image i =im.getImage();

                g.drawImage(i,0,0,this.getSize().width,this.getSize().height,this);

            }

        };
        backg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtMilli = new javax.swing.JTextField();
        txtreorder = new javax.swing.JTextField();
        pyes = new javax.swing.JRadioButton();
        pno = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug ID", "Drug name", "Milligrams", "Prescription", "Re Order qty"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form");

        jLabel2.setText("Drug Name");

        jLabel3.setText("Milligrams");

        jLabel5.setText("Prescription");

        jLabel6.setText("ReOrder Qty");

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtMilli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMilliActionPerformed(evt);
            }
        });

        pyes.setText("Needed");
        pyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyesActionPerformed(evt);
            }
        });

        pno.setText("Not needed");
        pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnoActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pyes)
                            .addComponent(txtName)
                            .addComponent(txtMilli)
                            .addComponent(txtreorder)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMilli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pyes))
                .addGap(18, 18, 18)
                .addComponent(pno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtreorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setText("logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(DName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void table_update()
    {
        int c;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            insert=con1.prepareStatement("select * from drug where Name=?");
            String DrugName=DName.getSelectedItem().toString();
            insert.setString(1,DrugName);
            ResultSet rs=insert.executeQuery();
            ResultSetMetaData res=rs.getMetaData();
            c=res.getColumnCount();
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1;a<=c;a++)
                {
                    v2.add(rs.getString("DrugId"));
                     v2.add(rs.getString("Name"));
                      v2.add(rs.getString("Mgs"));
                       v2.add(rs.getString("Prescription"));
                      v2.add(rs.getString("ReOrderQty"));
                     
                      
                    
                }
                
                df.addRow(v2);
            }
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        
            
            
            
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int c;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            insert=con1.prepareStatement("select * from drug where Name=? and Available=?");
            String DrugName=DName.getSelectedItem().toString();
                   
            String available="1";
            insert.setString(1,DrugName);
            insert.setString(2,available);
            ResultSet rs=insert.executeQuery();
            ResultSetMetaData res=rs.getMetaData();
            c=res.getColumnCount();
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
           df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1;a<=c;a++)
                {
                    v2.add(rs.getString("DrugId"));
                     v2.add(rs.getString("Name"));
                      v2.add(rs.getString("Mgs"));
                      v2.add(rs.getString("Prescription"));
                      v2.add(rs.getString("ReOrderQty"));
                      
                      
                    
                }
                
                df.addRow(v2);
            }
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
        
            
            
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
        private void updateCombo(){
        
        String available="1";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            insert=con1.prepareStatement("select Name from drug where Available=?");
             insert.setString(1,available);
            
            ResultSet rs=insert.executeQuery();
            
             while(rs.next())
            {
                
               
                   
                    DName.addItem(rs.getString("Name"));
               
              
                //df.addRow(v2);
            }
             
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        
        }
         
        
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        NMain nd = new NMain();
        nd.setVisible(true);
 this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        //String drugid=did1.getText();
        String dname=txtName.getText();
        String reOrder =txtreorder.getText();
        boolean pres1=pyes.isSelected();
        boolean pres2=pno.isSelected();
        String mg=txtMilli.getText();
        String available="1";
        int flag=1;
        
       
        
        if(dname==null || reOrder==null||mg==null||result==null)
        {
            JOptionPane.showMessageDialog(this, "Please enter all details");
        }
         
        else if(mg!=null || reOrder!=null)
        {
            if(mg!=null)
            {
                if(txtMilli.getText().matches("\\d+")==false)
                {
                    JOptionPane.showMessageDialog(this, "Please enter a  valid Milligrams ");
                    
                }
                 else
                 {
                     int mgs=Integer.parseInt(txtMilli.getText());
                    
                    if(mgs>=5000)
                    {
                        JOptionPane.showMessageDialog(this, "Please enter a value milligrams ");
                    }
                     
                 }
                    
                    
                    
                    
            }
            
            if(reOrder!=null)
            {
                if(txtreorder.getText().matches("\\d+")==false)
                {
                    JOptionPane.showMessageDialog(this, "Please enter a  valid ReOrder qty ");
                    
                }
                
            }
            
            
        } 
        
        
        
        
        

        try {

            Class.forName("com.mysql.jdbc.Driver");

            con1 = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            

            int id = Integer.parseInt(df.getValueAt(selectedIndex, 0).toString());
            String name =txtName.getText();
            String milli = txtMilli.getText();
            String reorder = txtreorder.getText();
            insert=con1.prepareStatement("SELECT 1 from drug where Name = ? and Mgs = ?");
            insert.setString(1,name);
            insert.setString(2,milli);
            //insert.setString(1,reorder);
            
           // insert=con1.prepareStatement("SELECT 1 from drug where Name = ? and Mgs = ?");
           /* insert.setString(1,name);
            insert.setString(2,milli);
            insert.setString(3,reorder);*/
     
            ResultSet rs=insert.executeQuery();
            int result1  = 0;
            while(rs.next()){
                
               result1 =  rs.getInt(1);
            }
            if(result1 == 1){
                
                JOptionPane.showMessageDialog(this, "Drug Already Exists");
            }
            
            else
            {
               
                    
                    

            insert = con1.prepareStatement("update drug set Name = ?, Mgs = ?, ReOrderQty = ?,Available=? where DrugId = ?");
            
            insert.setString(1, name);
            insert.setString(2, milli);
            insert.setString(3, reorder);
             insert.setString(4, available);
          
            insert.setInt(5, id);

            insert.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Updated");
            table_update();

            //did1.setText("");
            txtName.setText("");
            txtMilli.setText("");
            txtreorder.setText("");
            txtName.requestFocus();
            }
            

        } catch (SQLException ex) {

            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnoActionPerformed
        if(pno.isSelected())
        {
           pyes.setSelected(false);
        }
        
        result=false; 
        // TODO add your handling code here:
    }//GEN-LAST:event_pnoActionPerformed

    private void txtMilliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMilliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMilliActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();

       // did1.setText(df.getValueAt(selectedIndex, 0).toString());
        txtName.setText(df.getValueAt(selectedIndex, 1).toString());
        txtMilli.setText(df.getValueAt(selectedIndex, 2).toString());
        txtreorder.setText(df.getValueAt(selectedIndex, 4).toString());
        
        /*if(df.getValueAt(selectedIndex, 3).toString.equals("1")){
            pyes.setSelected(true);
            pno.setSelected(false);
        }
        else{
            pno.setSeleted(true);
            pyes.setSelected(false);
        }*/
        
        
        
        /*pyes.setText(df.getValueAt(selectedIndex, 3).toString()); 
        pno.setText(df.getValueAt(selectedIndex, 3).toString());*/
       // txtroqty.setText(df.getValueAt(selectedIndex, 5).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void pyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyesActionPerformed
        if(pyes.isSelected())
        {
           pno.setSelected(false);
        }
        
        result= true;
        // TODO add your handling code here:
    }//GEN-LAST:event_pyesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
MainUI nd = new MainUI();
        nd.setVisible(true); 
         this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        //String drugid=did1.getText();
        String dname=txtName.getText();
        String reOrder =txtreorder.getText();
        boolean pres1=pyes.isSelected();
        boolean pres2=pno.isSelected();
        String mg=txtMilli.getText();
        int flag=1;
        
       
        
        if(dname==null || reOrder==null||mg==null||result==null)
        {
            JOptionPane.showMessageDialog(this, "Please enter all details");
        }
         
        else if(mg!=null || reOrder!=null)
        {
            if(mg!=null)
            {
                if(txtMilli.getText().matches("\\d+")==false)
                {
                    JOptionPane.showMessageDialog(this, "Please enter a  valid Milligrams ");
                    
                }
                 else
                 {
                     int mgs=Integer.parseInt(txtMilli.getText());
                    
                    if(mgs>=5000)
                    {
                        JOptionPane.showMessageDialog(this, "Please enter a value milligrams ");
                    }
                     
                 }
                    
                    
                    
                    
            }
            
            if(reOrder!=null)
            {
                if(txtreorder.getText().matches("\\d+")==false)
                {
                    JOptionPane.showMessageDialog(this, "Please enter a  valid ReOrder qty ");
                    
                }
                
            }
            
            
        } 
        
        
        
        
        

        try {

            Class.forName("com.mysql.jdbc.Driver");

            con1 = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            

            int id = Integer.parseInt(df.getValueAt(selectedIndex, 0).toString());
            String name ="0";
            String milli = txtMilli.getText();
            String reorder = txtreorder.getText();
           
            //insert.setString(1,reorder);
            
           // insert=con1.prepareStatement("SELECT 1 from drug where Name = ? and Mgs = ?");
           /* insert.setString(1,name);
            insert.setString(2,milli);
            insert.setString(3,reorder);*/
     
            ResultSet rs=insert.executeQuery();
            int result1  = 0;
            while(rs.next()){
                
               result1 =  rs.getInt(1);
            }
            
            
               
                    
                    

            insert = con1.prepareStatement("update drug set Available=? where DrugId = ?");
            insert.setString(1, name);
            insert.setInt(2, id);

            insert.executeUpdate();
            
            insert2=con1.prepareStatement("update order1 set Available=? where DrugId = ?");
            
            insert2.setString(1, name);
            insert2.setInt(2, id);

            insert2.executeUpdate();

            JOptionPane.showMessageDialog(this, "Record Deleted");
            table_update();

            //did1.setText("");
            txtName.setText("");
            txtMilli.setText("");
            txtreorder.setText("");
            txtName.requestFocus();
            
            

        } catch (SQLException ex) {

            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
       
          
            
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NDrugDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DName;
    private javax.swing.JLabel backg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton pno;
    private javax.swing.JRadioButton pyes;
    private javax.swing.JTextField txtMilli;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtreorder;
    // End of variables declaration//GEN-END:variables
}
