/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class NStockDetails extends javax.swing.JFrame {

    /**
     * Creates new form NStockDetails
     */
    Connection con1;
    PreparedStatement insert;
    public NStockDetails() {
        initComponents();
        setimg();
        updateCombo();
        
    }
    
    private void setimg()
    {
        ImageIcon imageicon = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\icon.png");
        Image img = imageicon.getImage();
        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
        
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        backg.setIcon(scaledIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){

                ImageIcon im = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\backg1.jpg");
                Image i =im.getImage();

                g.drawImage(i,0,0,this.getSize().width,this.getSize().height,this);

            }

        };
        backg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pt = new javax.swing.JTextField();
        pf = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        drugid = new javax.swing.JLabel();
        stockid = new javax.swing.JLabel();
        edate = new com.toedter.calendar.JDateChooser();
        mdate = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        Dname = new javax.swing.JComboBox<>();
        Mg = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Form");

        jLabel2.setText("Drug ID");

        jLabel3.setText("stock ID");

        jLabel4.setText("Price To");

        jLabel5.setText("Price From");

        jLabel6.setText("Quantity");

        jLabel7.setText("Exp Date");

        jLabel8.setText("Manu Date");

        pt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptActionPerformed(evt);
            }
        });

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        edate.setDateFormatString("yyyy-MM-dd");

        mdate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(qty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(drugid, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stockid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(drugid, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stockid, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(mdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug ID", "Stock ID", "Drug Name", "Price To", "Price From", "Quantity", "Exp Date", "Manu Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnameActionPerformed(evt);
            }
        });

        Mg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MgActionPerformed(evt);
            }
        });

        jButton5.setText("logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Dname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(Mg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(Dname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        String drugid1=this.drugid.getText();
        String stockid1 =this.stockid.getText();
        String pto=pt.getText(); 
        String pfrom=pf.getText();
        String qtty=qty.getText();
        String edate1=sd.format(edate.getDate());
        String mdate1=sd.format(mdate.getDate());
        String available="1";
        
        if(drugid1==null || stockid1==null||pto==null||pfrom==null|| qtty==null)
        {
            JOptionPane.showMessageDialog(this, "Please enter all details");
        }
        
        else if(pto!=null || pfrom!=null||qtty!=null)
         {
             
             if(pto.matches("\\d+")==false)
             {
                 JOptionPane.showMessageDialog(this, "Please enter a Valid Price to ");
                 
             }
             else if(pfrom.matches("\\d+")==false)
             {
                 JOptionPane.showMessageDialog(this, "Please enter a Valid Price from ");
                 
             }
             else if(qtty.matches("\\d+")==false)
             {
                 JOptionPane.showMessageDialog(this, "Please enter a Valid quantity ");
                 
             }
             
            
             
         
             else
            {
                
                /*SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
                Date e1 = null;
                Date m1 = null;
                int to=Integer.parseInt(pto);
                    int from=Integer.parseInt(pfrom);
                 try {
                     e1 = sd.parse(edate1);
                 } catch (ParseException ex) {
                     Logger.getLogger(NStockAdd.class.getName()).log(Level.SEVERE, null, ex);
                 }

                try {
                    m1 = sd.parse(mdate1);
                } catch (ParseException ex) {
                    Logger.getLogger(NStockAdd.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            
            
            
            try {
                

                Class.forName("com.mysql.jdbc.Driver");

                con1 = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
                int to=Integer.parseInt(pto);
                    int from=Integer.parseInt(pfrom);
                
                if(edate1.compareTo(mdate1)<0)
                {
                   JOptionPane.showMessageDialog(this, "Invalid date"); 
                }
                else if(to<from)
                {
                    JOptionPane.showMessageDialog(this, "Invalid Prices "); 
                    
                }
                
                else
                {   

                insert = con1.prepareStatement("update order1 set ExpDate = ?, ManuDate = ?, PriceTo = ? ,PriceFrom=?,NoOfTablets=?,QtyLeft=?,Available=?where DrugID = ? and StockID=?");

                insert.setString(1, edate1);
                insert.setString(2, mdate1);
                insert.setString(3, pto);
                insert.setString(4, pfrom);
                insert.setString(5, qtty);
                insert.setString(6, qtty);
                insert.setString(8, drugid1);
                insert.setString(9, stockid1);
                  insert.setString(7,available); 
          
            

                insert.executeUpdate();

                JOptionPane.showMessageDialog(this, "Record Updated");
                //table_update();

                //drugid1.setText("");
                //stockid2.setText("");
                pt.setText("");
                pf.setText("");
                qty.setText("");
                edate.setDate(null);
                mdate.setDate(null);

               // drugid1.requestFocus();
                
                }
                }catch (SQLException ex) {

                    Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
                }

                }
         }
                                // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptActionPerformed
    private void updateCombo(){
        
        String available="1";
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            insert=con1.prepareStatement("select Name from drug where Available=?");
             insert.setString(1,available);
            
            ResultSet rs=insert.executeQuery();
            
             while(rs.next())
            {
                
               
                   
                    Dname.addItem(rs.getString("Name"));
               
              
                //df.addRow(v2);
            }
             String name=Dname.getSelectedItem().toString();
              insert=con1.prepareStatement("select distinct Mgs from drug where Available=? and Name=?");
             insert.setString(1,available);
             insert.setString(2,name);
            
            ResultSet rs1=insert.executeQuery();
            
             while(rs1.next())
            {
                
               
                   
                   Mg.addItem(rs1.getString("Mgs"));
               
              
                //df.addRow(v2);
            }
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        
        }
         
        
    }
    
    private void updatecombo2()
    {
        String available="1";
        String name=Dname.getSelectedItem().toString();

        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            insert=con1.prepareStatement("select Mgs from drug where Available=? and Name=?");
             insert.setString(1,available);
             insert.setString(2,name);
            
            ResultSet rs=insert.executeQuery();
            
             while(rs.next())
            {
                
               
                   
                   Mg.addItem(rs.getString("Mgs"));
               
              
                //df.addRow(v2);
            }
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    String available="1";
    int c;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
           // insert=con1.prepareStatement("select * from drug ,order1 where order1.DrugID=drug.DrugId and drug.DrugId=(select DrugId from drug where Name=?)");
           insert=con1.prepareStatement("select * from drug ,order1 where order1.DrugID=drug.DrugId and Name = ? and Mgs=? and order1.Available=?");
           
           String DrugName=Dname.getSelectedItem().toString();
           String mgs=Mg.getSelectedItem().toString();
            insert.setString(1,DrugName);
            insert.setString(2,mgs);
            insert.setString(3,available);
            ResultSet rs=insert.executeQuery();
            ResultSetMetaData res=rs.getMetaData();
            c=res.getColumnCount();
            DefaultTableModel df=(DefaultTableModel) jTable1.getModel();
           df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2=new Vector();
                for(int a=1;a<=c;a++)
                {
                    v2.add(rs.getString("DrugId"));
                    v2.add(rs.getString("StockID"));
                     v2.add(rs.getString("Name"));
                      v2.add(rs.getString("PriceTo"));
                      v2.add(rs.getString("PriceFrom"));
                      v2.add(rs.getString("NoOfTablets"));
                      v2.add(rs.getString("ExpDate"));
                      v2.add(rs.getString("ManuDate"));
                      
                      
                    
                }
                
                df.addRow(v2);
            }
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
        
            
            
            
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  NMain nd = new NMain();
        nd.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();

        drugid.setText(df.getValueAt(selectedIndex, 0).toString());
        stockid.setText(df.getValueAt(selectedIndex, 1).toString());
        pt.setText(df.getValueAt(selectedIndex, 3).toString()); 
         pf.setText(df.getValueAt(selectedIndex, 4).toString());
         qty.setText(df.getValueAt(selectedIndex, 5).toString()); 
         
         Date edate1,mdate1;
         try{
             edate1=(Date) new SimpleDateFormat("yyyy-MM-dd").parse(df.getValueAt(selectedIndex, 6).toString());
             edate.setDate(edate1);
             
             mdate1=(Date) new SimpleDateFormat("yyyy-MM-dd").parse(df.getValueAt(selectedIndex, 7).toString());
             mdate.setDate(edate1);
             
             
             
         }             
        catch (ParseException ex) {
        Logger.getLogger(NStockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         //edate.setText(df.getValueAt(selectedIndex, 6).toString());
        // mdate.setText(df.getValueAt(selectedIndex, 7).toString());
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        String drugid1=this.drugid.getText();
        String stockid1 =this.stockid.getText();
        String pto=pt.getText(); 
        String pfrom=pf.getText();
        String qtty=qty.getText();
        
        SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
        String edate1=sd.format(edate.getDate());
        String mdate1=sd.format(mdate.getDate());
        String available="0";
        
        if(drugid1==null || stockid1==null||pto==null||pfrom==null|| qtty==null)
        {
            JOptionPane.showMessageDialog(this, "Please enter all details");
        }
        
        else if(pto!=null || pfrom!=null||qtty!=null)
         {
             
             if(pto.matches("\\d+")==false)
             {
                 JOptionPane.showMessageDialog(this, "Please enter a Valid Price to ");
                 
             }
             else if(pfrom.matches("\\d+")==false)
             {
                 JOptionPane.showMessageDialog(this, "Please enter a Valid Price from ");
                 
             }
             else if(qtty.matches("\\d+")==false)
             {
                 JOptionPane.showMessageDialog(this, "Please enter a Valid quantity ");
                 
             }
             
            
             
         
             else
            {
                
               /* SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
                Date e1 = null;
                Date m1 = null;
                
                 try {
                     e1 = sd.parse(edate1);
                 } catch (ParseException ex) {
                     Logger.getLogger(NStockAdd.class.getName()).log(Level.SEVERE, null, ex);
                 }

                try {
                    m1 = sd.parse(mdate1);
                } catch (ParseException ex) {
                    Logger.getLogger(NStockAdd.class.getName()).log(Level.SEVERE, null, ex);
                }*/
            
            
            
            try {
                

                Class.forName("com.mysql.jdbc.Driver");
                int to=Integer.parseInt(pto);
                    int from=Integer.parseInt(pfrom);

                con1 = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
                
                if(edate1.compareTo(mdate1)<0)
                {
                   JOptionPane.showMessageDialog(this, "Invalid date"); 
                }
                else if(to<from)
                {
                    JOptionPane.showMessageDialog(this, "Invalid Prices "); 
                    
                }
                
                else
                {   

                insert = con1.prepareStatement("update order1 set ExpDate = ?, ManuDate = ?, PriceTo = ? ,PriceFrom=?,NoOfTablets=?,QtyLeft=?,Available=? where DrugID = ? and StockID=?");

                insert.setString(1, edate1);
                insert.setString(2, mdate1);
                insert.setString(3, pto);
                insert.setString(4, pfrom);
                insert.setString(5, qtty);
                insert.setString(6, qtty);
                insert.setString(8, drugid1);
                insert.setString(9, stockid1);
                  insert.setString(7,available); 
          
            

                insert.executeUpdate();

                JOptionPane.showMessageDialog(this, "Record Deleted successfully");
                //table_update();

                //drugid1.setText("");
                //stockid2.setText("");
                pt.setText("");
                pf.setText("");
                qty.setText("");
                edate.setDate(null);
                mdate.setDate(null);

               // drugid1.requestFocus();
                
                }
                }catch (SQLException ex) {

                    Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NDrugDetails.class.getName()).log(Level.SEVERE, null, ex);
                }

                }
         }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnameActionPerformed
        // TODO add your handling code here:
        
        String available="1";
        String name=Dname.getSelectedItem().toString();

        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con1=DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            Mg.removeAllItems();
            insert=con1.prepareStatement("select Mgs from drug where Available=? and Name=?");
             insert.setString(1,available);
             insert.setString(2,name);
            
            ResultSet rs=insert.executeQuery();
            
             while(rs.next())
            {
                
               
                   
                   Mg.addItem(rs.getString("Mgs"));
               
              
                //df.addRow(v2);
            }
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(NAddDrugForm.class.getName()).log(Level.SEVERE, null, ex);
        
        }
        
        
    }//GEN-LAST:event_DnameActionPerformed

    private void MgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MgActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_MgActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainUI nd = new MainUI();
        nd.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NStockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NStockDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Dname;
    private javax.swing.JComboBox<String> Mg;
    private javax.swing.JLabel backg;
    private javax.swing.JLabel drugid;
    private com.toedter.calendar.JDateChooser edate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser mdate;
    private javax.swing.JTextField pf;
    private javax.swing.JTextField pt;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel stockid;
    // End of variables declaration//GEN-END:variables
}
