/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;


import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Pcash extends javax.swing.JFrame {

    /**
     * Creates new form Pcash
     */
    public Pcash() {
        initComponents();
        setimg();
    }
    
    String totamount;
    String patientID;
    String billNO;
    String billTYPE;
    
    public Pcash(String totamount,String patientID,String billNO,String billTYPE) {
        initComponents();
        
        this.totamount=totamount;
        amount.setText(totamount);
        amount.setEditable(false);
        
        this.patientID=patientID;
        patientId.setText(patientID);
        patientId.setEditable(false);
        
        this.billNO=billNO;
        billNumber.setText(billNO);
        billNumber.setEditable(false);
        
        this.billTYPE=billTYPE;
        billType.setText(billTYPE);
        billType.setEditable(false);
        
    }
    
     public void setimg(){
        ImageIcon imageicon = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\icon.png");
        Image img = imageicon.getImage();
        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        backg.setIcon(scaledIcon);
        
    };
     
    private void displayTable(){
         
         int count;
     
          try{
            Class.forName("com.mysql.jdbc.Driver");
	
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            String sql2 = "select Bill_No,User_Id,Payers_Name,Bill_Type,Payment_Method,Date,Time,Amount from payment order by Bill_No DESC LIMIT 1";
            PreparedStatement result1 = conn.prepareStatement(sql2);
            ResultSet retrieve1 = result1.executeQuery();
            ResultSetMetaData r = retrieve1.getMetaData();
            
            count = r.getColumnCount();
            
              DefaultTableModel df = (DefaultTableModel) cashDetails.getModel();
              df.setRowCount(0);
              
              while(retrieve1.next()){
                  
                  Vector v = new Vector();
                  
                  for(int a=1; a<=count;a++){
                      
                      v.add(retrieve1.getString("Bill_No"));
                      v.add(retrieve1.getString("User_Id"));
                      v.add(retrieve1.getString("Payers_Name"));
                      v.add(retrieve1.getString("Bill_Type"));
                      v.add(retrieve1.getString("Payment_Method"));
                      v.add(retrieve1.getString("Date"));
                      v.add(retrieve1.getString("Time"));
                      v.add(retrieve1.getString("Amount"));
                  
                  }
                  
                  df.addRow(v);
              }
                     
        }catch(Exception ex){
         
      }
        
    }                                 
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){

                ImageIcon im = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\backg1.jpg");
                Image i =im.getImage();

                g.drawImage(i,0,0,this.getSize().width,this.getSize().height,this);

            }
        };
        backg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        payersName = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        billNumber = new javax.swing.JTextField();
        patientId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cashDetails = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        billType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nameMsg = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Enter Payer's Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Payer's Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Amount");

        payersName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        payersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payersNameActionPerformed(evt);
            }
        });
        payersName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                payersNameKeyPressed(evt);
            }
        });

        amount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Patient Id");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Bill Number");

        billNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        billNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNumberActionPerformed(evt);
            }
        });

        patientId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        patientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cashDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Patient Id", "Payer's Name", "Bill Type", "Payment Method", "Date", "Time", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cashDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cashDetails);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        billType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Bill Type");

        nameMsg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton7.setText("logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton3)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(patientId)
                                    .addComponent(billNumber)
                                    .addComponent(payersName)
                                    .addComponent(amount)
                                    .addComponent(billType, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(nameMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton7)))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(billNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(patientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(nameMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(payersName.getText().equals("")){
        
            JOptionPane.showMessageDialog(this,"Please enter all the details");
        }
        
        else{
                try{
                   Class.forName("com.mysql.jdbc.Driver");

                   Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");

                   String sql1 = "insert into payment(Bill_No,Payers_Name,Bill_Type,Payment_Method,Amount,User_Id,Status) values (?,?,?,?,?,?,?)";
                   PreparedStatement insert1 = conn.prepareStatement(sql1);
                   String payMethod="Cash";

                   String status = "Paid";
                   
                   insert1.setString(1,billNumber.getText());
                   insert1.setString(2,payersName.getText());
                   insert1.setString(3,billType.getText());
                   insert1.setString(4,payMethod);
                   insert1.setDouble(5,Double.parseDouble(amount.getText()));
                   insert1.setString(6,patientId.getText());
                   insert1.setString(7,status);
                   

                   insert1.executeUpdate();

                   JOptionPane.showMessageDialog(this,"Record is Inserted");

                   displayTable();

                   billNumber.setText("");
                   patientId.setText("");
                   payersName.setText("");
                   billType.setText("");
                   amount.setText("");


               }catch(Exception ex){

                 JOptionPane.showMessageDialog(this,"Record already exists");

             } 
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void payersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payersNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
           Class.forName("com.mysql.jdbc.Driver");
	
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            String sql2 = "delete from payment where Bill_No='"+billNumber.getText()+"'";
            PreparedStatement delete = conn.prepareStatement(sql2);
            
           
            delete.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record is Deleted");
            
            String totamount=amount.getText();
            String patientID=patientId.getText();
            String billNO=billNumber.getText();
            
            new Pcreditcard(totamount,patientID,billNO,billTYPE).setVisible(true);
            this.dispose();
            
              
        }catch(Exception ex){
            
          JOptionPane.showMessageDialog(this,"Record No Deleted");
             
      } 
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void billNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNumberActionPerformed

    private void patientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIdActionPerformed

    private void cashDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashDetailsMouseClicked
        
        DefaultTableModel df = (DefaultTableModel) cashDetails.getModel();
        int selectedIndex = cashDetails.getSelectedRow();
        
        billNumber.setText(df.getValueAt(selectedIndex,0).toString());
        patientId.setText(df.getValueAt(selectedIndex,1).toString());
        payersName.setText(df.getValueAt(selectedIndex,2).toString());
        billType.setText(df.getValueAt(selectedIndex,3).toString());
        amount.setText(df.getValueAt(selectedIndex,7).toString());
    }//GEN-LAST:event_cashDetailsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
	
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            
            Double am = Double.parseDouble(amount.getText());
            int billNo = Integer.parseInt(billNumber.getText());
            
            
            String sql1 = "update payment set Payers_Name='"+payersName.getText()+"' where Bill_No='"+billNumber.getText()+"'";
            PreparedStatement insert1 = conn.prepareStatement(sql1);
            
           
            insert1.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Record is Updated");
            
            displayTable();
            
           
        }catch(Exception ex){
            
          JOptionPane.showMessageDialog(this,"Record Not Updated");
             
      } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Pbills().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void payersNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payersNameKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
        
         payersName.setEditable(true);  
         nameMsg.setText("");
        }
        if(Character.isDigit(c)){
         
            nameMsg.setText("Letters Only");
        }
    }//GEN-LAST:event_payersNameKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        MainUI nd = new MainUI();
        nd.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pcash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel backg;
    private javax.swing.JTextField billNumber;
    private javax.swing.JTextField billType;
    private javax.swing.JTable cashDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameMsg;
    private javax.swing.JTextField patientId;
    private javax.swing.JTextField payersName;
    // End of variables declaration//GEN-END:variables
}
