/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagmentsystem;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.*;
import java.text.ParseException;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;




/**
 *
 * @author user
 */
public class Pcreditcard extends javax.swing.JFrame {
    public Pcreditcard() {
        initComponents();
        setimg();

    }
    String totamount;
    String patientID;
    String billNO;
    String billTYPE;
    
    public Pcreditcard(String totamount,String patientID,String billNO,String billTYPE) {
        initComponents();
        
        this.totamount=totamount;
        amount.setText(totamount);
        amount.setEditable(false);
        
        this.patientID=patientID;
        patientId.setText(patientID);
        patientId.setEditable(false);
        
        this.billNO=billNO;
        billNumber.setText(billNO);
        billNumber.setEditable(false);
        
        this.billTYPE=billTYPE;
        billType.setText(billTYPE);
        billType.setEditable(false);
    }
    
   
     public void setimg(){
        ImageIcon imageicon = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\icon.png");
        Image img = imageicon.getImage();
        Image imgScale = img.getScaledInstance(backg.getWidth(),backg.getHeight(),Image.SCALE_FAST);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        backg.setIcon(scaledIcon);
        
    };
     
     private void displayTable(){
         
         int count;
     
          try{
            Class.forName("com.mysql.jdbc.Driver");
	
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            String sql2 = "select Bill_No,User_Id,Payers_Name,Bill_Type,Payment_Method,Date,Time,Amount from payment order by Bill_No DESC LIMIT 1";
            PreparedStatement result1 = conn.prepareStatement(sql2);
            ResultSet retrieve1 = result1.executeQuery();
            ResultSetMetaData r = retrieve1.getMetaData();
            
            count = r.getColumnCount();
            
              DefaultTableModel df = (DefaultTableModel) creditDetails.getModel();
              df.setRowCount(0);
              
              while(retrieve1.next()){
                  
                  Vector v = new Vector();
                  
                  for(int a=1; a<=count;a++){
                      
                      v.add(retrieve1.getString("Bill_No"));
                      v.add(retrieve1.getString("User_Id"));
                      v.add(retrieve1.getString("Payers_Name"));
                      v.add(retrieve1.getString("Bill_Type"));
                      v.add(retrieve1.getString("Payment_Method"));
                      v.add(retrieve1.getString("Date"));
                      v.add(retrieve1.getString("Time"));
                      v.add(retrieve1.getString("Amount"));
                  
                  }
                  
                  df.addRow(v);
              }
                     
        }catch(Exception ex){
         
      }
        
    }  
     
     
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){

                ImageIcon im = new ImageIcon("C:\\Users\\Chathunika Heenkenda\\Desktop\\ITP Project\\Main Project\\interfaces\\HospitalManagmentSystem\\src\\images\\backg1.jpg");
                Image i =im.getImage();

                g.drawImage(i,0,0,this.getSize().width,this.getSize().height,this);

            }
        };
        backg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billNumber = new javax.swing.JTextField();
        cardHoldersName = new javax.swing.JTextField();
        cardNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        creditDetails = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        patientId = new javax.swing.JTextField();
        expiryDate = new com.toedter.calendar.JDateChooser();
        creditMsg = new javax.swing.JLabel();
        dateMsg = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        billType = new javax.swing.JTextField();
        nameMsg = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Enter Credit Card Details");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Card Holder's Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Card Number");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Expiry Date");

        billNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        billNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNumberActionPerformed(evt);
            }
        });

        cardHoldersName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cardHoldersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardHoldersNameActionPerformed(evt);
            }
        });
        cardHoldersName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardHoldersNameKeyPressed(evt);
            }
        });

        cardNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });
        cardNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cardNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cardNumberKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Amount");

        amount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        creditDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Patient Id", "Card Holder's Name", "Bill Type", "Payment Method", "Date", "Time", "Amount"
            }
        ));
        creditDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(creditDetails);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Patient Id");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Bill Number");

        patientId.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        expiryDate.setDateFormatString("yyyy-MM-dd");
        expiryDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        creditMsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        dateMsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Bill Type");

        billType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        nameMsg.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jButton7.setText("logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(creditMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(124, 124, 124)
                                                .addComponent(jButton1)
                                                .addGap(58, 58, 58)
                                                .addComponent(jButton5))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(dateMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButton3))
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton2)
                                .addGap(60, 60, 60)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(billType, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(billNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(patientId))
                                    .addComponent(cardHoldersName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nameMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton7)))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(billNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(billType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cardHoldersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(creditMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String payMethod="Credit";
       
            if(cardHoldersName.getText().equals("") || cardNumber.getText().equals("")||expiryDate.getDate()==null){
       
            JOptionPane.showMessageDialog(this,"Please enter all the details");
            }
        
            else if(creditMsg.getText()=="Invalid Credit Card"){
            
               JOptionPane.showMessageDialog(this,"Please enter a valid Credit Card Number");
            
            }
            else if(dateMsg.getText()=="Expired"){
            
                JOptionPane.showMessageDialog(this,"The Credit Card is Expired");
            }
            else{
        
                try{
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");

                    String sql = "insert into payment(Bill_No,Payers_Name,Bill_Type,Payment_Method,Amount,User_Id,Status) values (?,?,?,?,?,?,?)";
                    PreparedStatement insert = conn.prepareStatement(sql);
                    
                    String status = "Paid";

                    insert.setString(1,billNumber.getText());
                    insert.setString(2,cardHoldersName.getText());
                    insert.setString(3,billType.getText());
                    insert.setString(4,payMethod);
                    
                    //SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
                    //insert.setString(4,sd.format(expiryDate.getDate()));

                    insert.setDouble(5,Double.parseDouble(amount.getText()));
                    insert.setString(6,patientId.getText());
                    insert.setString(7,status);

                    insert.executeUpdate();

                    JOptionPane.showMessageDialog(this,"Record Inserted");

                    displayTable();


                    billNumber.setText("");
                    patientId.setText("");
                    cardHoldersName.setText("");
                    billType.setText("");
                    amount.setText("");
                    
                    dateMsg.setText("Valid Cresit Card");
                    creditMsg.setText("Not Expired");
                    
                }catch(Exception ex){

                  JOptionPane.showMessageDialog(this,"Record already exists");
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void billNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNumberActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_billNumberActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
	
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
            
            String cardName= cardHoldersName.getText();
            
            //SimpleDateFormat sd=new SimpleDateFormat("yyyy-MM-dd");
            //String date1=sd.format(expiryDate.getDate());
      
            int billNo = Integer.parseInt(billNumber.getText());
            
            
            String sql1 = "update payment set Payers_Name='"+cardName+"'where Bill_No='"+billNo+"'";
            PreparedStatement insert1 = conn.prepareStatement(sql1);
            
            insert1.executeUpdate();
            
          
            JOptionPane.showMessageDialog(this,"Record Is Updated");
            
            displayTable();
            
           
              
        }catch(Exception ex){
            
          JOptionPane.showMessageDialog(this,"Record Not Updated");
             
      } 
                                        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cardHoldersNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardHoldersNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardHoldersNameActionPerformed

    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_cardNumberActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
            
         
                  try{
                     Class.forName("com.mysql.jdbc.Driver");
	
                    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/hms","root","");
                 
                    String sql2 = "delete from payment where Bill_No='"+billNumber.getText()+"'";
                    PreparedStatement delete = conn.prepareStatement(sql2);

                    delete.executeUpdate();


                    JOptionPane.showMessageDialog(this,"Record Is Deleted");

                    String totamount=amount.getText();
                    String patientID=patientId.getText();
                    String billNO=billNumber.getText();
                    
                    new Pcash(totamount,patientID,billNO,billTYPE).setVisible(true);



                    billNumber.setText("");
                    patientId.setText("");
                    cardHoldersName.setText("");
                    //cardNumber.setText("");
                    //expiryDate.setDate(null);
                    amount.setText("");

                    this.dispose();

                }catch(Exception ex){

                  JOptionPane.showMessageDialog(this,"Record is not Deleted");

              } 
        
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void creditDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditDetailsMouseClicked
        
        DefaultTableModel df = (DefaultTableModel) creditDetails.getModel();
        int selectedIndex = creditDetails.getSelectedRow();
        
        billNumber.setText(df.getValueAt(selectedIndex,0).toString());
        patientId.setText(df.getValueAt(selectedIndex,1).toString());
        billType.setText(df.getValueAt(selectedIndex,2).toString());
        cardHoldersName.setText(df.getValueAt(selectedIndex,3).toString());
      
        amount.setText(df.getValueAt(selectedIndex,7).toString());
        
        //dateMsg.setText("Not Expired");
        //creditMsg.setText("Valid Credit Card");
        
        //Date date;
        
       /* try {
            date= (Date) new SimpleDateFormat("yyyy-MM-dd").parse(df.getValueAt(selectedIndex,4).toString());
            expiryDate.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Pcreditcard.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
       
        
        
        
    }//GEN-LAST:event_creditDetailsMouseClicked

    private void cardNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyReleased
        // TODO add your handling code here:
        
        String creditNum = cardNumber.getText();
        
        
        int[] ints = new int[creditNum.length()];
        
		for (int i = 0; i < creditNum.length(); i++) 
                {
			ints[i] = Integer.parseInt(creditNum.substring(i, i + 1));
		}
                
		for (int i = ints.length - 2; i >= 0; i = i - 2) 
                {
			int j = ints[i];
			j = j * 2;
                        
			if (j > 9) 
                        {
				j = j % 10 + 1;
			}
                        
			ints[i] = j;
		}
                
		int sum = 0;
                
		for (int i = 0; i < ints.length; i++)
                {
			sum += ints[i];
		}
                
		if (sum % 10 == 0 && creditNum.length()==16) 
                {
			creditMsg.setText("Valid Credit Card");
		} 
                else 
                {
			creditMsg.setText("Invalid Credit Card");
		}
    }//GEN-LAST:event_cardNumberKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
        String d1 = sd.format(expiryDate.getDate());
        String d2 = java.time.LocalDate.now().toString();
        
        if(d1.compareTo(d2)<0){
            dateMsg.setText("Expired");
        }
        else
        {
            dateMsg.setText("Not Expired");
        }
        
        String creditNum = cardNumber.getText();
        
        int[] ints = new int[creditNum.length()];
        
		for (int i = 0; i < creditNum.length(); i++) 
                {
			ints[i] = Integer.parseInt(creditNum.substring(i, i + 1));
		}
                
		for (int i = ints.length - 2; i >= 0; i = i - 2) 
                {
			int j = ints[i];
			j = j * 2;
                        
			if (j > 9) 
                        {
				j = j % 10 + 1;
			}
                        
			ints[i] = j;
		}
                
		int sum = 0;
                
		for (int i = 0; i < ints.length; i++)
                {
			sum += ints[i];
		}
                
		if (sum % 10 == 0 && creditNum.length()==16) 
                {
           
			creditMsg.setText("Valid Credit Card");
		} 
                else
                {
			creditMsg.setText("Invalid Credit Card");
		}
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new Pbills().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cardHoldersNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardHoldersNameKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c)){
        
         cardHoldersName.setEditable(true);  
         nameMsg.setText("");
        }
        if(Character.isDigit(c)){
         
            nameMsg.setText("Letters Only");
        }
        
    }//GEN-LAST:event_cardHoldersNameKeyPressed

    private void cardNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberKeyPressed
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        
          if(Character.isDigit(c)){
         
            creditMsg.setText("");
         }
          
          
        if(Character.isLetter(c)){
        
         cardNumber.setEditable(true);  
         creditMsg.setText("Numbers Only");
        }
        
        
    }//GEN-LAST:event_cardNumberKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        MainUI nd = new MainUI();
        nd.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pcreditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pcreditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pcreditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pcreditcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pcreditcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField amount;
    private javax.swing.JLabel backg;
    public javax.swing.JTextField billNumber;
    private javax.swing.JTextField billType;
    private javax.swing.JTextField cardHoldersName;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JTable creditDetails;
    private javax.swing.JLabel creditMsg;
    private javax.swing.JLabel dateMsg;
    private com.toedter.calendar.JDateChooser expiryDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameMsg;
    private javax.swing.JTextField patientId;
    // End of variables declaration//GEN-END:variables
}
